CREATE TABLE IF NOT EXISTS images (
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    description TEXT DEFAULT "",
    h INTEGER NOT NULL DEFAULT 6,
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    i INTEGER GENERATED ALWAYS AS (id) STORED,
    name TEXT NOT NULL,
    pathname TEXT NOT NULL,
    stats_likes INTEGER NOT NULL DEFAULT 0,
    stats_views INTEGER NOT NULL DEFAULT 0,
    stats_downloads INTEGER NOT NULL DEFAULT 0,
    sum INTEGER GENERATED ALWAYS AS (x + y) STORED,
    sum_abs INTEGER GENERATED ALWAYS AS (ABS(x) + ABS(y)) STORED,
    tags TEXT DEFAULT '[]',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    w INTEGER NOT NULL DEFAULT 6,
    x INTEGER NOT NULL DEFAULT 0,
    y INTEGER NOT NULL DEFAULT 0
);